// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package gqlmodel

import (
	"time"
)

// A session.
type AuthPayload struct {
	// A short-lived signed token, sent as `Authorization: Bearer ...` on every
	// request. It is not revocable, which is why it is short-lived.
	AccessToken string `json:"accessToken"`
	// A long-lived opaque token, sent only to `refresh`.
	//
	// It is single-use. Each refresh returns a new one and invalidates the old,
	// and presenting an already-spent token revokes the entire chain back to the
	// login that started it -- on the reasoning that two parties holding a secret
	// meant for one is indistinguishable from theft.
	RefreshToken string `json:"refreshToken"`
	// When the access token stops being accepted.
	ExpiresAt time.Time `json:"expiresAt"`
	User      *User     `json:"user"`
}

type DeleteResult struct {
	// False when the post was already deleted. Deleting is idempotent.
	Deleted bool   `json:"deleted"`
	ID      string `json:"id"`
}

type FollowResult struct {
	// False when the edge already existed. Following is idempotent.
	Changed bool  `json:"changed"`
	User    *User `json:"user"`
}

type Mutation struct {
}

type PageInfo struct {
	HasNextPage bool    `json:"hasNextPage"`
	EndCursor   *string `json:"endCursor,omitempty"`
}

type PostConnection struct {
	Edges    []*PostEdge `json:"edges"`
	PageInfo *PageInfo   `json:"pageInfo"`
}

type PostEdge struct {
	Node   *Post  `json:"node"`
	Cursor string `json:"cursor"`
}

type Query struct {
}

type Subscription struct {
}
