// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package gqlmodel

type DeleteResult struct {
	// False when the post was already deleted. Deleting is idempotent.
	Deleted bool   `json:"deleted"`
	ID      string `json:"id"`
}

type FollowResult struct {
	// False when the edge already existed. Following is idempotent.
	Changed bool  `json:"changed"`
	User    *User `json:"user"`
}

type Mutation struct {
}

type PageInfo struct {
	HasNextPage bool    `json:"hasNextPage"`
	EndCursor   *string `json:"endCursor,omitempty"`
}

type PostConnection struct {
	Edges    []*PostEdge `json:"edges"`
	PageInfo *PageInfo   `json:"pageInfo"`
}

type PostEdge struct {
	Node   *Post  `json:"node"`
	Cursor string `json:"cursor"`
}

type Query struct {
}

type Subscription struct {
}
