package gateway

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"
	"strings"

	authv1 "github.com/anwexhaa/murmur/api/gen/murmur/auth/v1"
	socialv1 "github.com/anwexhaa/murmur/api/gen/murmur/social/v1"
	timelinev1 "github.com/anwexhaa/murmur/api/gen/murmur/timeline/v1"
	"github.com/anwexhaa/murmur/internal/gateway/gqlgen"
	"github.com/anwexhaa/murmur/internal/gateway/gqlmodel"
)

// CreatePost is the resolver for the createPost field.
func (r *mutationResolver) CreatePost(ctx context.Context, body string) (*gqlmodel.Post, error) {
	viewer, err := requireViewer(ctx)
	if err != nil {
		return nil, err
	}

	resp, err := r.Clients.Social.CreatePost(ctx, &socialv1.CreatePostRequest{
		AuthorId: viewer,
		Body:     body,
	})
	if err != nil {
		return nil, r.translate(ctx, "createPost", err)
	}
	return postFromProto(resp.GetPost()), nil
}

// DeletePost removes a post the caller wrote.
//
// Soft delete: the ID is already in a great many Redis timelines, and the read
// path skips IDs it cannot hydrate. Removing the row would leave those entries
// as permanent silent gaps.
func (r *mutationResolver) DeletePost(ctx context.Context, id string) (*gqlmodel.DeleteResult, error) {
	viewer, err := requireViewer(ctx)
	if err != nil {
		return nil, err
	}

	resp, err := r.Clients.Social.DeletePost(ctx, &socialv1.DeletePostRequest{
		Id:      id,
		ActorId: viewer,
	})
	if err != nil {
		return nil, r.translate(ctx, "deletePost", err)
	}
	return &gqlmodel.DeleteResult{Deleted: resp.GetDeleted(), ID: id}, nil
}

// Follow is the resolver for the follow field.
func (r *mutationResolver) Follow(ctx context.Context, userID string) (*gqlmodel.FollowResult, error) {
	viewer, err := requireViewer(ctx)
	if err != nil {
		return nil, err
	}

	resp, err := r.Clients.Social.Follow(ctx, &socialv1.FollowRequest{
		FollowerId: viewer,
		FolloweeId: userID,
	})
	if err != nil {
		return nil, r.translate(ctx, "follow", err)
	}

	target, err := r.Clients.Social.GetUser(ctx, &socialv1.GetUserRequest{
		Key: &socialv1.GetUserRequest_Id{Id: userID},
	})
	if err != nil {
		return nil, r.translate(ctx, "follow.user", err)
	}

	return &gqlmodel.FollowResult{
		Changed: resp.GetCreated(),
		User:    userFromProto(target.GetUser()),
	}, nil
}

// Unfollow is the resolver for the unfollow field.
func (r *mutationResolver) Unfollow(ctx context.Context, userID string) (*gqlmodel.FollowResult, error) {
	viewer, err := requireViewer(ctx)
	if err != nil {
		return nil, err
	}

	resp, err := r.Clients.Social.Unfollow(ctx, &socialv1.UnfollowRequest{
		FollowerId: viewer,
		FolloweeId: userID,
	})
	if err != nil {
		return nil, r.translate(ctx, "unfollow", err)
	}

	target, err := r.Clients.Social.GetUser(ctx, &socialv1.GetUserRequest{
		Key: &socialv1.GetUserRequest_Id{Id: userID},
	})
	if err != nil {
		return nil, r.translate(ctx, "unfollow.user", err)
	}

	return &gqlmodel.FollowResult{
		Changed: resp.GetRemoved(),
		User:    userFromProto(target.GetUser()),
	}, nil
}

// Register is the resolver for the register field.
func (r *mutationResolver) Register(ctx context.Context, handle string, displayName string, password string) (*gqlmodel.AuthPayload, error) {
	if r.Sessions == nil {
		return nil, r.translate(ctx, "register", errNoSessions)
	}
	// Throttled by client address rather than by handle: the handle is chosen
	// by the caller, so limiting on it means one bucket per attempt and no
	// limit at all.
	if err := r.throttle(ctx, ScopeRegister, clientKey(ctx)); err != nil {
		return nil, err
	}

	created, err := r.Clients.Auth.Register(ctx, &authv1.RegisterRequest{
		Handle:      handle,
		DisplayName: displayName,
		Password:    password,
	})
	if err != nil {
		return nil, r.translate(ctx, "register", err)
	}

	payload, err := r.Sessions.start(ctx, created.GetUserId(), created.GetHandle())
	if err != nil {
		return nil, r.translate(ctx, "register", err)
	}
	return payload, nil
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, handle string, password string) (*gqlmodel.AuthPayload, error) {
	if r.Sessions == nil {
		return nil, r.translate(ctx, "login", errNoSessions)
	}

	// Two buckets, because they stop different attacks. The per-handle one
	// stops a password being guessed against one account from many addresses;
	// the per-address one stops many accounts being tried from one address,
	// which is what credential stuffing actually looks like. Either alone
	// leaves the other wide open.
	if err := r.throttle(ctx, ScopeLogin, strings.ToLower(handle)); err != nil {
		return nil, err
	}
	if err := r.throttle(ctx, ScopeLoginSource, clientKey(ctx)); err != nil {
		return nil, err
	}

	authenticated, err := r.Clients.Auth.Authenticate(ctx, &authv1.AuthenticateRequest{
		Handle:   handle,
		Password: password,
	})
	if err != nil {
		return nil, r.translate(ctx, "login", err)
	}

	payload, err := r.Sessions.start(ctx, authenticated.GetUserId(), authenticated.GetHandle())
	if err != nil {
		return nil, r.translate(ctx, "login", err)
	}
	return payload, nil
}

// Refresh is the resolver for the refresh field.
func (r *mutationResolver) Refresh(ctx context.Context, refreshToken string) (*gqlmodel.AuthPayload, error) {
	if r.Sessions == nil {
		return nil, r.translate(ctx, "refresh", errNoSessions)
	}
	if err := r.throttle(ctx, ScopeRefresh, clientKey(ctx)); err != nil {
		return nil, err
	}

	rotated, err := r.Clients.Auth.RotateRefreshToken(ctx, &authv1.RotateRefreshTokenRequest{
		RefreshToken: refreshToken,
	})
	if err != nil {
		return nil, r.translate(ctx, "refresh", err)
	}

	payload, err := r.Sessions.issue(ctx,
		rotated.GetUserId(), "", rotated.GetRefreshToken(), asTime(rotated.GetExpiresAt()))
	if err != nil {
		return nil, r.translate(ctx, "refresh", err)
	}
	return payload, nil
}

// Logout is the resolver for the logout field.
func (r *mutationResolver) Logout(ctx context.Context, refreshToken string) (bool, error) {
	if r.Sessions == nil {
		return false, r.translate(ctx, "logout", errNoSessions)
	}

	// No viewer required. A client whose access token has already expired
	// still needs to be able to end its session, and refusing would leave the
	// refresh token live for another thirty days out of pedantry.
	if _, err := r.Clients.Auth.RevokeSession(ctx, &authv1.RevokeSessionRequest{
		Key: &authv1.RevokeSessionRequest_RefreshToken{RefreshToken: refreshToken},
	}); err != nil {
		return false, r.translate(ctx, "logout", err)
	}
	return true, nil
}

// ChangePassword is the resolver for the changePassword field.
func (r *mutationResolver) ChangePassword(ctx context.Context, currentPassword string, newPassword string) (bool, error) {
	viewer, err := requireViewer(ctx)
	if err != nil {
		return false, err
	}
	if err := r.throttle(ctx, ScopeLogin, viewer); err != nil {
		return false, err
	}

	if _, err := r.Clients.Auth.ChangePassword(ctx, &authv1.ChangePasswordRequest{
		UserId:          viewer,
		CurrentPassword: currentPassword,
		NewPassword:     newPassword,
	}); err != nil {
		return false, r.translate(ctx, "changePassword", err)
	}
	return true, nil
}

// Author was the canonical N+1: one call per post, and fifty identical calls
// for a page by one author. It is now one batched call per request, and the
// duplicate-author case costs a single key.
//
// Note what did not change — the resolver still looks like it fetches one
// user, because from its own point of view it does. The batching lives in the
// loader, which is why this rewrite could not disturb the measurement.
func (r *postResolver) Author(ctx context.Context, obj *gqlmodel.Post) (*gqlmodel.User, error) {
	loaders := LoadersFrom(ctx)
	if loaders == nil {
		return nil, r.translate(ctx, "post.author", errNoLoaders)
	}

	user, err := loaders.Users.Load(ctx, obj.AuthorID)
	if err != nil {
		return nil, r.translate(ctx, "post.author", err)
	}
	if user == nil {
		// The author was deleted after the post. The post is still real, so
		// this is a null author rather than a failed request.
		return nil, nil
	}
	return user, nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*gqlmodel.User, error) {
	viewer, err := requireViewer(ctx)
	if err != nil {
		return nil, err
	}

	resp, err := r.Clients.Social.GetUser(ctx, &socialv1.GetUserRequest{
		Key: &socialv1.GetUserRequest_Id{Id: viewer},
	})
	if err != nil {
		return nil, r.translate(ctx, "me", err)
	}
	return userFromProto(resp.GetUser()), nil
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, handle string) (*gqlmodel.User, error) {
	resp, err := r.Clients.Social.GetUser(ctx, &socialv1.GetUserRequest{
		Key: &socialv1.GetUserRequest_Handle{Handle: handle},
	})
	if err != nil {
		return nil, r.translate(ctx, "user", err)
	}
	return userFromProto(resp.GetUser()), nil
}

// Post is the resolver for the post field.
func (r *queryResolver) Post(ctx context.Context, id string) (*gqlmodel.Post, error) {
	resp, err := r.Clients.Social.GetPost(ctx, &socialv1.GetPostRequest{Id: id})
	if err != nil {
		return nil, r.translate(ctx, "post", err)
	}
	return postFromProto(resp.GetPost()), nil
}

// Timeline reads a feed that was materialised at write time.
//
// One call, regardless of how many accounts the viewer follows. Phase 2
// assembled this at read time — list who you follow, ask each of them for
// recent posts, merge — which cost one call per followed account on every
// single read. The fanout worker now does that work once per post instead,
// and this became a range query behind a single RPC.
//
// The cost did not disappear; it moved to the side of the trade that is paid
// less often. Reads outnumber writes in a feed by roughly a hundred to one.
func (r *queryResolver) Timeline(ctx context.Context, first *int, after *string) (*gqlmodel.PostConnection, error) {
	viewer, err := requireViewer(ctx)
	if err != nil {
		return nil, err
	}

	limit := pageSize(first, 50, maxPostPage)

	cursor := ""
	if after != nil {
		cursor = *after
	}

	resp, err := r.Clients.Timeline.GetTimeline(ctx, &timelinev1.GetTimelineRequest{
		UserId:    viewer,
		PageSize:  int32(limit),
		PageToken: cursor,
	})
	if err != nil {
		return nil, r.translate(ctx, "timeline", err)
	}

	posts := make([]*gqlmodel.Post, 0, len(resp.GetPosts()))
	for _, p := range resp.GetPosts() {
		posts = append(posts, postFromProto(p))
	}

	conn := connection(posts, limit)
	// The service decides whether another page exists, because it knows how
	// many IDs it read before hydration. Posts deleted since fanout make the
	// returned page shorter than the page that was actually traversed, and
	// inferring "no more pages" from a short page would end the feed early.
	if token := resp.GetNextPageToken(); token != "" {
		conn.PageInfo.HasNextPage = true
		conn.PageInfo.EndCursor = &token
	} else {
		conn.PageInfo.HasNextPage = false
	}
	return conn, nil
}

// TimelineUpdates streams posts arriving on the caller's timeline.
//
// Three things happen here, in order, and the order is the design:
//
//  1. Subscribe first, so nothing published during the replay below is missed.
//     Subscribing after the replay would leave a window exactly as wide as the
//     replay takes.
//  2. Replay what the client missed since its cursor, bounded to one page.
//  3. Switch to live delivery.
//
// The pump runs in its own goroutine and owns the outgoing channel — it is the
// only writer and the only closer, which is what keeps this free of the
// send-on-closed-channel race that a hub closing its own channel would create.
func (r *subscriptionResolver) TimelineUpdates(ctx context.Context, after *string) (<-chan *gqlmodel.TimelineUpdate, error) {
	viewer, err := requireViewer(ctx)
	if err != nil {
		return nil, err
	}
	if r.Hub == nil {
		return nil, r.translate(ctx, "timelineUpdates", errNoHub)
	}

	sub, err := r.Hub.Subscribe(viewer)
	if err != nil {
		return nil, r.translate(ctx, "timelineUpdates", err)
	}

	out := make(chan *gqlmodel.TimelineUpdate, subscriptionOutBuffer)

	go func() {
		defer close(out)
		defer sub.Close()

		missed, gapped := r.replay(ctx, viewer, after)
		for _, update := range missed {
			if update.Gap {
				gapped = false
			}
			select {
			case out <- update:
			case <-ctx.Done():
				return
			}
		}

		// A gap the replay could not deliver — because the replay itself
		// failed and produced nothing — has to survive into live delivery.
		// Dropping it here would leave the client believing it has an
		// unbroken stream while a hole sits behind its cursor, which is the
		// one failure a gap flag exists to prevent.
		for {
			select {
			case <-ctx.Done():
				return

			case <-sub.Done():
				// Evicted for falling too far behind. Ending the stream is the
				// signal: a client that is told nothing cannot know to reconnect.
				return

			case update := <-sub.Updates:
				resolved := r.hydrateUpdate(ctx, update)
				if resolved == nil {
					continue
				}
				if gapped {
					resolved.Gap = true
					gapped = false
				}
				select {
				case out <- resolved:
				case <-ctx.Done():
					return
				}
			}
		}
	}()

	return out, nil
}

// FollowerCount was the second N+1. Batched.
func (r *userResolver) FollowerCount(ctx context.Context, obj *gqlmodel.User) (int, error) {
	loaders := LoadersFrom(ctx)
	if loaders == nil {
		return 0, r.translate(ctx, "user.followerCount", errNoLoaders)
	}

	count, err := loaders.FollowerCounts.Load(ctx, obj.ID)
	if err != nil {
		return 0, r.translate(ctx, "user.followerCount", err)
	}
	return count, nil
}

// ViewerFollows is the third. It is null rather than false when nobody is
// signed in: "we did not ask" and "no" are different answers, and a client
// rendering a Follow button needs to tell them apart.
func (r *userResolver) ViewerFollows(ctx context.Context, obj *gqlmodel.User) (*bool, error) {
	viewer := Viewer(ctx)
	if viewer == "" {
		return nil, nil
	}
	if viewer == obj.ID {
		following := false
		return &following, nil
	}

	loaders := LoadersFrom(ctx)
	if loaders == nil {
		return nil, r.translate(ctx, "user.viewerFollows", errNoLoaders)
	}

	// The batch form of IsFollowing is FilterFollowing, which phase 4 already
	// needed for the read path's pull side. One query answers fifty resolvers.
	following, err := loaders.ViewerFollows.Load(ctx, obj.ID)
	if err != nil {
		return nil, r.translate(ctx, "user.viewerFollows", err)
	}
	return &following, nil
}

// Posts is the resolver for the posts field.
func (r *userResolver) Posts(ctx context.Context, obj *gqlmodel.User, first *int, after *string) (*gqlmodel.PostConnection, error) {
	limit := pageSize(first, defaultPostPage, maxPostPage)

	cursor := ""
	if after != nil {
		cursor = *after
	}

	resp, err := r.Clients.Social.ListAuthorPosts(ctx, &socialv1.ListAuthorPostsRequest{
		AuthorId:  obj.ID,
		PageSize:  int32(limit),
		PageToken: cursor,
	})
	if err != nil {
		return nil, r.translate(ctx, "user.posts", err)
	}

	posts := make([]*gqlmodel.Post, 0, len(resp.GetPosts()))
	for _, p := range resp.GetPosts() {
		posts = append(posts, postFromProto(p))
	}
	return connection(posts, limit), nil
}

// Mutation returns gqlgen.MutationResolver implementation.
func (r *Resolver) Mutation() gqlgen.MutationResolver { return &mutationResolver{r} }

// Post returns gqlgen.PostResolver implementation.
func (r *Resolver) Post() gqlgen.PostResolver { return &postResolver{r} }

// Query returns gqlgen.QueryResolver implementation.
func (r *Resolver) Query() gqlgen.QueryResolver { return &queryResolver{r} }

// Subscription returns gqlgen.SubscriptionResolver implementation.
func (r *Resolver) Subscription() gqlgen.SubscriptionResolver { return &subscriptionResolver{r} }

// User returns gqlgen.UserResolver implementation.
func (r *Resolver) User() gqlgen.UserResolver { return &userResolver{r} }

type (
	mutationResolver     struct{ *Resolver }
	postResolver         struct{ *Resolver }
	queryResolver        struct{ *Resolver }
	subscriptionResolver struct{ *Resolver }
	userResolver         struct{ *Resolver }
)
