package gateway

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"

	socialv1 "github.com/anwexhaa/murmur/api/gen/murmur/social/v1"
	"github.com/anwexhaa/murmur/internal/gateway/gqlgen"
	"github.com/anwexhaa/murmur/internal/gateway/gqlmodel"
	"golang.org/x/sync/errgroup"
)

// CreatePost is the resolver for the createPost field.
func (r *mutationResolver) CreatePost(ctx context.Context, body string) (*gqlmodel.Post, error) {
	viewer, err := requireViewer(ctx)
	if err != nil {
		return nil, err
	}

	resp, err := r.Clients.Social.CreatePost(ctx, &socialv1.CreatePostRequest{
		AuthorId: viewer,
		Body:     body,
	})
	if err != nil {
		return nil, r.translate(ctx, "createPost", err)
	}
	return postFromProto(resp.GetPost()), nil
}

// Follow is the resolver for the follow field.
func (r *mutationResolver) Follow(ctx context.Context, userID string) (*gqlmodel.FollowResult, error) {
	viewer, err := requireViewer(ctx)
	if err != nil {
		return nil, err
	}

	resp, err := r.Clients.Social.Follow(ctx, &socialv1.FollowRequest{
		FollowerId: viewer,
		FolloweeId: userID,
	})
	if err != nil {
		return nil, r.translate(ctx, "follow", err)
	}

	target, err := r.Clients.Social.GetUser(ctx, &socialv1.GetUserRequest{
		Key: &socialv1.GetUserRequest_Id{Id: userID},
	})
	if err != nil {
		return nil, r.translate(ctx, "follow.user", err)
	}

	return &gqlmodel.FollowResult{
		Changed: resp.GetCreated(),
		User:    userFromProto(target.GetUser()),
	}, nil
}

// Unfollow is the resolver for the unfollow field.
func (r *mutationResolver) Unfollow(ctx context.Context, userID string) (*gqlmodel.FollowResult, error) {
	viewer, err := requireViewer(ctx)
	if err != nil {
		return nil, err
	}

	resp, err := r.Clients.Social.Unfollow(ctx, &socialv1.UnfollowRequest{
		FollowerId: viewer,
		FolloweeId: userID,
	})
	if err != nil {
		return nil, r.translate(ctx, "unfollow", err)
	}

	target, err := r.Clients.Social.GetUser(ctx, &socialv1.GetUserRequest{
		Key: &socialv1.GetUserRequest_Id{Id: userID},
	})
	if err != nil {
		return nil, r.translate(ctx, "unfollow.user", err)
	}

	return &gqlmodel.FollowResult{
		Changed: resp.GetRemoved(),
		User:    userFromProto(target.GetUser()),
	}, nil
}

// Author is the canonical N+1. One call per post in the page, every one of
// them a separate round trip, and a timeline of fifty posts by one author
// makes the same lookup fifty times.
func (r *postResolver) Author(ctx context.Context, obj *gqlmodel.Post) (*gqlmodel.User, error) {
	resp, err := r.Clients.Social.GetUser(ctx, &socialv1.GetUserRequest{
		Key: &socialv1.GetUserRequest_Id{Id: obj.AuthorID},
	})
	if err != nil {
		return nil, r.translate(ctx, "post.author", err)
	}
	return userFromProto(resp.GetUser()), nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*gqlmodel.User, error) {
	viewer, err := requireViewer(ctx)
	if err != nil {
		return nil, err
	}

	resp, err := r.Clients.Social.GetUser(ctx, &socialv1.GetUserRequest{
		Key: &socialv1.GetUserRequest_Id{Id: viewer},
	})
	if err != nil {
		return nil, r.translate(ctx, "me", err)
	}
	return userFromProto(resp.GetUser()), nil
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, handle string) (*gqlmodel.User, error) {
	resp, err := r.Clients.Social.GetUser(ctx, &socialv1.GetUserRequest{
		Key: &socialv1.GetUserRequest_Handle{Handle: handle},
	})
	if err != nil {
		return nil, r.translate(ctx, "user", err)
	}
	return userFromProto(resp.GetUser()), nil
}

// Post is the resolver for the post field.
func (r *queryResolver) Post(ctx context.Context, id string) (*gqlmodel.Post, error) {
	resp, err := r.Clients.Social.GetPost(ctx, &socialv1.GetPostRequest{Id: id})
	if err != nil {
		return nil, r.translate(ctx, "post", err)
	}
	return postFromProto(resp.GetPost()), nil
}

// Timeline assembles a home feed by pulling from every account the viewer
// follows and merging the results.
//
// This is the design phase 3 exists to delete. Its cost is proportional to how
// many accounts you follow, it pays that cost on every read rather than once
// per write, and it over-fetches by design because any one account could
// supply the entire page. Reads outnumber writes in a social feed by roughly
// a hundred to one, so paying at read time is the expensive side of the trade.
//
// The fan-out runs concurrently — the naive design is being measured, not
// handicapped. Sequential calls would make the numbers look worse than the
// design deserves, and a "before" that is unfairly slow makes the "after"
// unfairly good.
func (r *queryResolver) Timeline(ctx context.Context, first *int, after *string) (*gqlmodel.PostConnection, error) {
	viewer, err := requireViewer(ctx)
	if err != nil {
		return nil, err
	}

	limit := pageSize(first, 50, maxPostPage)

	following, err := r.Clients.Social.ListFollowing(ctx, &socialv1.ListFollowingRequest{
		UserId:   viewer,
		PageSize: int32(r.fanout()),
	})
	if err != nil {
		return nil, r.translate(ctx, "timeline.following", err)
	}

	authors := following.GetFolloweeIds()
	if len(authors) == 0 {
		return connection(nil, limit), nil
	}

	cursor := ""
	if after != nil {
		cursor = *after
	}

	streams := make([][]*gqlmodel.Post, len(authors))
	group, groupCtx := errgroup.WithContext(ctx)
	// Bounded: an account following hundreds of people should not open
	// hundreds of simultaneous calls and convert its own slow query into
	// everyone else's slow query.
	group.SetLimit(16)

	for i, author := range authors {
		group.Go(func() error {
			resp, err := r.Clients.Social.ListAuthorPosts(groupCtx, &socialv1.ListAuthorPostsRequest{
				AuthorId:  author,
				PageSize:  timelineFetchPerAuthor,
				PageToken: cursor,
			})
			if err != nil {
				return err
			}
			posts := make([]*gqlmodel.Post, 0, len(resp.GetPosts()))
			for _, p := range resp.GetPosts() {
				posts = append(posts, postFromProto(p))
			}
			streams[i] = posts
			return nil
		})
	}

	if err := group.Wait(); err != nil {
		return nil, r.translate(ctx, "timeline.posts", err)
	}

	return connection(mergePostsNewestFirst(streams, limit), limit), nil
}

// FollowerCount is the second N+1: once per user in the response, and a
// timeline resolves one user per post.
func (r *userResolver) FollowerCount(ctx context.Context, obj *gqlmodel.User) (int, error) {
	resp, err := r.Clients.Social.GetFollowerCount(ctx, &socialv1.GetFollowerCountRequest{
		UserId: obj.ID,
	})
	if err != nil {
		return 0, r.translate(ctx, "user.followerCount", err)
	}
	return int(resp.GetFollowers()), nil
}

// ViewerFollows is the third. It is null rather than false when nobody is
// signed in: "we did not ask" and "no" are different answers, and a client
// rendering a Follow button needs to tell them apart.
func (r *userResolver) ViewerFollows(ctx context.Context, obj *gqlmodel.User) (*bool, error) {
	viewer := Viewer(ctx)
	if viewer == "" {
		return nil, nil
	}
	if viewer == obj.ID {
		following := false
		return &following, nil
	}

	resp, err := r.Clients.Social.IsFollowing(ctx, &socialv1.IsFollowingRequest{
		FollowerId: viewer,
		FolloweeId: obj.ID,
	})
	if err != nil {
		return nil, r.translate(ctx, "user.viewerFollows", err)
	}

	following := resp.GetFollowing()
	return &following, nil
}

// Posts is the resolver for the posts field.
func (r *userResolver) Posts(ctx context.Context, obj *gqlmodel.User, first *int, after *string) (*gqlmodel.PostConnection, error) {
	limit := pageSize(first, defaultPostPage, maxPostPage)

	cursor := ""
	if after != nil {
		cursor = *after
	}

	resp, err := r.Clients.Social.ListAuthorPosts(ctx, &socialv1.ListAuthorPostsRequest{
		AuthorId:  obj.ID,
		PageSize:  int32(limit),
		PageToken: cursor,
	})
	if err != nil {
		return nil, r.translate(ctx, "user.posts", err)
	}

	posts := make([]*gqlmodel.Post, 0, len(resp.GetPosts()))
	for _, p := range resp.GetPosts() {
		posts = append(posts, postFromProto(p))
	}
	return connection(posts, limit), nil
}

// Mutation returns gqlgen.MutationResolver implementation.
func (r *Resolver) Mutation() gqlgen.MutationResolver { return &mutationResolver{r} }

// Post returns gqlgen.PostResolver implementation.
func (r *Resolver) Post() gqlgen.PostResolver { return &postResolver{r} }

// Query returns gqlgen.QueryResolver implementation.
func (r *Resolver) Query() gqlgen.QueryResolver { return &queryResolver{r} }

// User returns gqlgen.UserResolver implementation.
func (r *Resolver) User() gqlgen.UserResolver { return &userResolver{r} }

type (
	mutationResolver struct{ *Resolver }
	postResolver     struct{ *Resolver }
	queryResolver    struct{ *Resolver }
	userResolver     struct{ *Resolver }
)
